language: node_js
sudo: false
node_js:
  - '6.6.0'

cache:
  directories:
     - ./node_modules
     - ./.chrome/chromium

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: npm install

script: npm test

notifications:
  slack:
    on_success: always
    on_failure: always 
  email:
    recipients:
      - demoiselle-devel@lists.sourceforge.net
    on_success: never
    on_failure: always
